spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/express-money-tracker-db
    username: postgres
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

app:
  jwtSecret: lucky_7seven_lucky_7seven_lucky_7
  jwtRefreshSecret: ${APP_JWTREFRESHSECRET:}

server:
  port: 8081

org:
  slf4j:
    simpleLogger:
      defaultLogLevel: debug

